### ISSUE TITLE
FYI: ClangQL is great and "PyQL" would be too.

### ISSUE THREAD

**Issue by galenseilis** [AmrDeveloper/ClangQL#9]
Hi, I think that this tool is a great idea.

I am wondering if such a tool exists for Python, and I have asked about this on [SE](https://softwarerecs.stackexchange.com/questions/91543/is-there-a-python-query-language-tool-like-clangql).

This is just an FYI. Feel free to close without additional actions.

**Comment by AmrDeveloper** [comment]
Hello @galenseilis,

Thank you for the suggestion, it's cool idea and possible to implement, maybe i can start a MVP and accept feature request and contributors to make it grow, and thanks for the name :D, i will notify you once i create a basic version.

Thank you,
Amr

**Comment by AmrDeveloper** [comment]
PyQL 0.1.0 is released, currently is working with functions, and step by step support other features and pattern matching :D

https://github.com/AmrDeveloper/PyQL

Thank you for the suggestion, and feel free to write a feedback, suggest ideas, report bugs :D

We can close this issue now and all new issues can be on PyQL Repo.

Can you please write your Linkedin & Twitter username so i can give you shot out when i publish it

Thank you

**Comment by Dominiquini** [comment]
You have plans to release compiled binaries of this application for Windows, Linux and MacOS?

Thanks.

**Comment by AmrDeveloper** [comment]
> You have plans to release compiled binaries of this application for Windows, Linux and MacOS?
> 
> Thanks.

For PyQL i already released binaries, for ClangQL yes i need to modify the release process to install LLVM first and then link with it, but i need to do some improvements first then i will work on the release pipeline

Thanks

**Comment by galenseilis** [comment]
> PyQL 0.1.0 is released, currently is working with functions, and step by step support other features and pattern matching :D
> 
> https://github.com/AmrDeveloper/PyQL
> 
> Thank you for the suggestion, and feel free to write a feedback, suggest ideas, report bugs :D
> 
> We can close this issue now and all new issues can be on PyQL Repo.
> 
> Can you please write your Linkedin & Twitter username so i can give you shot out when i publish it
> 
> Thank you

Impressive! I am looking forward to trying this out! Thank you for your hard work. 🙏

https://www.linkedin.com/in/%F0%9F%90%8D-galen-s-4208349b/
